language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - os: osx
      brew_packages: v8
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

addons:
  apt:
    packages:
      - libv8-dev

notifications:
  email:
    on_success: change
    on_failure: change
