language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - os: osx
      brew_packages: v8 --force-bottle
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

addons:
  apt:
    packages:
      - libv8-dev

notifications:
  email:
    on_success: change
    on_failure: change
